image: jdrouet/docker-with-buildx:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

# This is called for all non-tagged commits just to confirm the image will build
# but it does not push the image to the container registry.
build:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 .
    - echo "This image will be tagged as registry.gitlab.com/michael.tiller/book-builder-image:$(CI_COMMIT_TAG)"
    # - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag your-username/multiarch-example:gitlab .
  rules:
    - if: "$CI_COMMIT_TAG != null"
      when: never

# This is called for tagged commits and pushes the resulting image into the container
# registry.
publish:
  stage: build
  script:
    - docker buildx create --use
    - docker buildx build --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag registry.gitlab.com/michael.tiller/book-builder-image:$(CI_COMMIT_TAG) .
    - echo "This image will be tagged as registry.gitlab.com/michael.tiller/book-builder-image:$(CI_COMMIT_TAG)"
    # - docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64 --tag your-username/multiarch-example:gitlab .
  rules:
    - if: "$CI_COMMIT_TAG != null"
      when: always
